name = "HexGrids"
uuid = "958768e3-a6c4-4c00-bfc1-a372889203e3"
authors = ["Jared Lumpe <jared@jaredlumpe.com>"]
version = "0.1.0"

[deps]
Requires = "ae029012-a4dd-5104-9daa-d747884805df"

[weakdeps]
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[extensions]
PlotlyExt = "PlotlyJS"
